// <auto-generated />
using System;
using CasaRositaFact.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasaRositaFact.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250511232156_CrecionModelosParaModuloFactura")]
    partial class CrecionModelosParaModuloFactura
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CasaRositaFact.Models.Articulo", b =>
                {
                    b.Property<int>("IdArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdArticulo"));

                    b.Property<decimal?>("CantidadMinima")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CodigoProducto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoIngreso")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int?>("IdRubro")
                        .HasColumnType("int");

                    b.Property<int?>("IdUnidadMedida")
                        .HasColumnType("int");

                    b.Property<bool>("LlevarStock")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("StockActual")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdArticulo");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdRubro");

                    b.HasIndex("IdUnidadMedida");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Banco", b =>
                {
                    b.Property<int>("IdBanco")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBanco"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdBanco");

                    b.ToTable("Bancos");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CUIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRegimenImpositivo")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipoDocumentoIdTipoDocumento")
                        .HasColumnType("int");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdRegimenImpositivo");

                    b.HasIndex("IdTipoDocumento");

                    b.HasIndex("TipoDocumentoIdTipoDocumento");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("CasaRositaFact.Models.ConceptoFactura", b =>
                {
                    b.Property<int>("IdConceptoFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConceptoFactura"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdConceptoFactura");

                    b.ToTable("ConceptosFacturas");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpresa"));

                    b.Property<int?>("CodigoPostal")
                        .HasColumnType("int");

                    b.Property<string>("CondicionIva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cuit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Domicilio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaExpiracionCertificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("IIBB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InicioActividad")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreFantasia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RutaCertificado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerieCertificado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEmpresa");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<bool>("Anulada")
                        .HasColumnType("bit");

                    b.Property<string>("BVFactura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BVReferencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Descuento")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdConceptoFactura")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdFormaPago")
                        .HasColumnType("int");

                    b.Property<int>("IdLetraFactura")
                        .HasColumnType("int");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoDocumentoFiscal")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuarioAnulacion")
                        .HasColumnType("int");

                    b.Property<bool>("Impresa")
                        .HasColumnType("bit");

                    b.Property<bool>("MoverStock")
                        .HasColumnType("bit");

                    b.Property<string>("NombreMaquina")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NroCompFactura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroCompReferencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SubTotal105")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SubTotal21")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TipoUsuarioIdTipoUsuario")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDescuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDescuento105")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDescuento21")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalInteres")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalInteresSaldando")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalIva105")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalIva21")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalSaldando")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdConceptoFactura");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdFormaPago");

                    b.HasIndex("IdLetraFactura");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("IdTipoDocumentoFiscal");

                    b.HasIndex("IdUsuario");

                    b.HasIndex("IdUsuarioAnulacion");

                    b.HasIndex("TipoUsuarioIdTipoUsuario");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("CasaRositaFact.Models.FacturaDetalle", b =>
                {
                    b.Property<int>("IdFacturaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFacturaDetalle"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool?>("DesdeRemito")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<int?>("IdRemito")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoIva")
                        .HasColumnType("int");

                    b.Property<int>("IdUnidadMedida")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("NombreArticulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PrecioManual")
                        .HasColumnType("bit");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalArticulo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdFacturaDetalle");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdFactura");

                    b.HasIndex("IdTipoIva");

                    b.HasIndex("IdUnidadMedida");

                    b.HasIndex("IdUsuario");

                    b.ToTable("FacturaDetalles");
                });

            modelBuilder.Entity("CasaRositaFact.Models.FormaPago", b =>
                {
                    b.Property<int>("IdFormaPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFormaPago"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFormaPago");

                    b.ToTable("FormasPago");
                });

            modelBuilder.Entity("CasaRositaFact.Models.LetraFactura", b =>
                {
                    b.Property<int>("IdLetraFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLetraFactura"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLetraFactura");

                    b.ToTable("LetrasFacturas");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Localidad", b =>
                {
                    b.Property<int>("IdLocalidad")
                        .HasColumnType("int");

                    b.Property<int>("IdProvincia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdLocalidad");

                    b.HasIndex("IdProvincia");

                    b.ToTable("Localidades");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Parametro", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadMaxItemFactura")
                        .HasColumnType("int");

                    b.Property<string>("ImpresoraPredeterminada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PorcentajeGanancia")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.HasKey("IdEmpresa");

                    b.ToTable("Parametros");
                });

            modelBuilder.Entity("CasaRositaFact.Models.PrecioArticulo", b =>
                {
                    b.Property<int>("IdPrecioArticulo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPrecioArticulo"));

                    b.Property<bool>("EsPrecioCosto")
                        .HasColumnType("bit");

                    b.Property<bool>("EsPrecioDescuento")
                        .HasColumnType("bit");

                    b.Property<bool>("EsPrecioLista")
                        .HasColumnType("bit");

                    b.Property<bool>("EsPrecioPublico")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaIncio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdArticulo")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoIva")
                        .HasColumnType("int")
                        .HasColumnName("IdTipoIva");

                    b.Property<decimal>("PorcentajeGanancia")
                        .HasPrecision(4, 1)
                        .HasColumnType("decimal(4,1)");

                    b.Property<decimal>("PrecioCosto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioDescuento")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioLista")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVentaConIva")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioVentaSinIva")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TipoIvaIdTipoIva")
                        .HasColumnType("int");

                    b.HasKey("IdPrecioArticulo");

                    b.HasIndex("IdArticulo");

                    b.HasIndex("IdTipoIva");

                    b.HasIndex("TipoIvaIdTipoIva");

                    b.ToTable("PreciosArticulos");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<string>("CBU")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUIT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdBanco")
                        .HasColumnType("int");

                    b.Property<string>("NombreContacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProveedor");

                    b.HasIndex("IdBanco");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Provincia", b =>
                {
                    b.Property<int>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProvincia"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProvincia");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("CasaRositaFact.Models.RegimenImpositivo", b =>
                {
                    b.Property<int>("IdRegimenImpositivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegimenImpositivo"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRegimenImpositivo");

                    b.ToTable("RegimenesImpositivos");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Rubro", b =>
                {
                    b.Property<int>("IdRubro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRubro"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRubro");

                    b.ToTable("Rubros");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Sucursal", b =>
                {
                    b.Property<int>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSucursal"));

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSucursal");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("CasaRositaFact.Models.TipoDocumento", b =>
                {
                    b.Property<int>("IdTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDocumento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoDocumento");

                    b.ToTable("TiposDocumentos");
                });

            modelBuilder.Entity("CasaRositaFact.Models.TipoDocumentoFiscal", b =>
                {
                    b.Property<int>("IdTipoDocumentoFiscal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDocumentoFiscal"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoDocumentoFiscal");

                    b.ToTable("TiposDocumentosFiscales");
                });

            modelBuilder.Entity("CasaRositaFact.Models.TipoIva", b =>
                {
                    b.Property<int>("IdTipoIva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoIva"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Porcentaje")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdTipoIva");

                    b.ToTable("TiposIva");
                });

            modelBuilder.Entity("CasaRositaFact.Models.TipoUsuario", b =>
                {
                    b.Property<int>("IdTipoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoUsuario"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoUsuario");

                    b.ToTable("TiposUsuarios");
                });

            modelBuilder.Entity("CasaRositaFact.Models.UnidadMedida", b =>
                {
                    b.Property<int>("IdUnidadMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidadMedida"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUnidadMedida");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("ClaveUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdSucursal")
                        .HasColumnType("int");

                    b.Property<int?>("IdTipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdSucursal");

                    b.HasIndex("IdTipoUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Articulo", b =>
                {
                    b.HasOne("CasaRositaFact.Models.Categoria", "Categoria")
                        .WithMany("Articulos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CasaRositaFact.Models.Proveedor", "Proveedor")
                        .WithMany("Articulos")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CasaRositaFact.Models.Rubro", "Rubro")
                        .WithMany("Articulos")
                        .HasForeignKey("IdRubro")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CasaRositaFact.Models.UnidadMedida", "UnidadMedida")
                        .WithMany("Articulos")
                        .HasForeignKey("IdUnidadMedida")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Categoria");

                    b.Navigation("Proveedor");

                    b.Navigation("Rubro");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Cliente", b =>
                {
                    b.HasOne("CasaRositaFact.Models.RegimenImpositivo", "RegimenImpositivo")
                        .WithMany()
                        .HasForeignKey("IdRegimenImpositivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CasaRositaFact.Models.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("IdTipoDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CasaRositaFact.Models.TipoDocumento", null)
                        .WithMany("Clientes")
                        .HasForeignKey("TipoDocumentoIdTipoDocumento");

                    b.Navigation("RegimenImpositivo");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Factura", b =>
                {
                    b.HasOne("CasaRositaFact.Models.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CasaRositaFact.Models.ConceptoFactura", "ConceptoFactura")
                        .WithMany("Facturas")
                        .HasForeignKey("IdConceptoFactura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CasaRositaFact.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CasaRositaFact.Models.FormaPago", "FormaPago")
                        .WithMany("Facturas")
                        .HasForeignKey("IdFormaPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CasaRositaFact.Models.LetraFactura", "LetraFactura")
                        .WithMany("Facturas")
                        .HasForeignKey("IdLetraFactura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CasaRositaFact.Models.Sucursal", "Sucursal")
                        .WithMany("Facturas")
                        .HasForeignKey("IdSucursal")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CasaRositaFact.Models.TipoDocumentoFiscal", "TipoDocumentoFiscal")
                        .WithMany("Facturas")
                        .HasForeignKey("IdTipoDocumentoFiscal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CasaRositaFact.Models.Usuario", "UsuarioGenerador")
                        .WithMany("FacturasGeneradas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CasaRositaFact.Models.Usuario", "UsuarioAnulador")
                        .WithMany("FacturasAnuladas")
                        .HasForeignKey("IdUsuarioAnulacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CasaRositaFact.Models.TipoUsuario", null)
                        .WithMany("Facturas")
                        .HasForeignKey("TipoUsuarioIdTipoUsuario");

                    b.Navigation("Cliente");

                    b.Navigation("ConceptoFactura");

                    b.Navigation("Empresa");

                    b.Navigation("FormaPago");

                    b.Navigation("LetraFactura");

                    b.Navigation("Sucursal");

                    b.Navigation("TipoDocumentoFiscal");

                    b.Navigation("UsuarioAnulador");

                    b.Navigation("UsuarioGenerador");
                });

            modelBuilder.Entity("CasaRositaFact.Models.FacturaDetalle", b =>
                {
                    b.HasOne("CasaRositaFact.Models.Articulo", "Articulo")
                        .WithMany("FacturaDetalles")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CasaRositaFact.Models.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CasaRositaFact.Models.TipoIva", "TipoIva")
                        .WithMany()
                        .HasForeignKey("IdTipoIva");

                    b.HasOne("CasaRositaFact.Models.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("IdUnidadMedida")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CasaRositaFact.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario");

                    b.Navigation("Articulo");

                    b.Navigation("Factura");

                    b.Navigation("TipoIva");

                    b.Navigation("UnidadMedida");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Localidad", b =>
                {
                    b.HasOne("CasaRositaFact.Models.Provincia", "Provincia")
                        .WithMany("Localidades")
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Parametro", b =>
                {
                    b.HasOne("CasaRositaFact.Models.Empresa", "Empresa")
                        .WithOne("Parametro")
                        .HasForeignKey("CasaRositaFact.Models.Parametro", "IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("CasaRositaFact.Models.PrecioArticulo", b =>
                {
                    b.HasOne("CasaRositaFact.Models.Articulo", "Articulo")
                        .WithMany("PreciosArticulos")
                        .HasForeignKey("IdArticulo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CasaRositaFact.Models.TipoIva", "TipoIva")
                        .WithMany()
                        .HasForeignKey("IdTipoIva")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CasaRositaFact.Models.TipoIva", null)
                        .WithMany("PreciosArticulos")
                        .HasForeignKey("TipoIvaIdTipoIva");

                    b.Navigation("Articulo");

                    b.Navigation("TipoIva");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Proveedor", b =>
                {
                    b.HasOne("CasaRositaFact.Models.Banco", "Banco")
                        .WithMany("Proveedores")
                        .HasForeignKey("IdBanco")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Banco");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Usuario", b =>
                {
                    b.HasOne("CasaRositaFact.Models.Sucursal", "Sucursal")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdSucursal");

                    b.HasOne("CasaRositaFact.Models.TipoUsuario", "TiposUsuarios")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdTipoUsuario");

                    b.Navigation("Sucursal");

                    b.Navigation("TiposUsuarios");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Articulo", b =>
                {
                    b.Navigation("FacturaDetalles");

                    b.Navigation("PreciosArticulos");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Banco", b =>
                {
                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Categoria", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Cliente", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("CasaRositaFact.Models.ConceptoFactura", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Empresa", b =>
                {
                    b.Navigation("Parametro")
                        .IsRequired();
                });

            modelBuilder.Entity("CasaRositaFact.Models.Factura", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("CasaRositaFact.Models.FormaPago", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("CasaRositaFact.Models.LetraFactura", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Proveedor", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Provincia", b =>
                {
                    b.Navigation("Localidades");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Rubro", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Sucursal", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CasaRositaFact.Models.TipoDocumento", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("CasaRositaFact.Models.TipoDocumentoFiscal", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("CasaRositaFact.Models.TipoIva", b =>
                {
                    b.Navigation("PreciosArticulos");
                });

            modelBuilder.Entity("CasaRositaFact.Models.TipoUsuario", b =>
                {
                    b.Navigation("Facturas");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("CasaRositaFact.Models.UnidadMedida", b =>
                {
                    b.Navigation("Articulos");
                });

            modelBuilder.Entity("CasaRositaFact.Models.Usuario", b =>
                {
                    b.Navigation("FacturasAnuladas");

                    b.Navigation("FacturasGeneradas");
                });
#pragma warning restore 612, 618
        }
    }
}
